version: '3.7'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - my_network
    volumes:
      - ${WEBAPP_STORAGE_HOME}/back:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=prod

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - NODE_ENV=prod
    networks:
      - my_network

networks:
  my_network:
    driver: bridge