version: '3.7'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - NODE_ENV=development
