# Étape 1: Construire l'application Angular dans un environnement Node.js
FROM node:14 as builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Étape 2: Servir l'application à partir d'un serveur Nginx
FROM nginx:alpine

COPY --from=builder /usr/src/app /usr/share/nginx/html

COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]